### ISSUE TITLE
Project Image Preview Not Loading

### ISSUE THREAD

**Issue by zshaian** [tjtanjin/portfolio-2#1]
## Description
In your projects section, there's two projects image preview that's not showing on the screen the **Spachips**, and **Survival Top**.

## Screenshot

![screenshot of the problem, where there's two missing project image preview](https://i.imgur.com/FZSfS4w.png)

## Aditional Context
- OS: **Windows**
- Browser: **Google Chrome**

**Comment by tjtanjin** [comment]
Hey @Bear-Frost, thank you for pointing this out. I've just done a quick fix and made some minor updates to the website 😊
